"""initial schema

Revision ID: 9e88fa0665cd
Revises: 
Create Date: 2026-08-13 02:25:49.230374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9e88fa0665cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('executedAt', sa.DateTime(), nullable=False),
    sa.Column('periodStart', sa.Date(), nullable=False),
    sa.Column('periodEnd', sa.Date(), nullable=False),
    sa.Column('reportName', sa.String(), nullable=False),
    sa.Column('posListFile', sa.String(), nullable=False),
    sa.Column('simoClosingsFile', sa.String(), nullable=False),
    sa.Column('bankaCreditsFile', sa.String(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_executedAt'), 'execution', ['executedAt'], unique=False)
    op.create_table('closing_detail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('executionId', sa.String(length=36), nullable=False),
    sa.Column('posId', sa.String(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('accountNumber', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('simoClosingDate', sa.Date(), nullable=False),
    sa.Column('operationNumber', sa.Integer(), nullable=False),
    sa.Column('simoClosingTotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('simoKeyTotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closingDescription', sa.String(), nullable=True),
    sa.Column('bankaCreditDate', sa.Date(), nullable=True),
    sa.Column('bankaClosingTotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closingType', sa.Enum('D', 'D_PLUS_1', 'NA', name='closing_type'), nullable=False),
    sa.Column('validation', sa.Enum('zero', 'match', 'mismatch', 'missing', 'duplicated', name='validation'), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['executionId'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_closing_detail_execution_key', 'closing_detail', ['executionId', 'key'], unique=False)
    op.create_index('ix_closing_detail_execution_pos_id', 'closing_detail', ['executionId', 'posId'], unique=False)
    op.create_index('ix_closing_detail_execution_validation', 'closing_detail', ['executionId', 'validation'], unique=False)
    op.create_table('credit_movement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('executionId', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('movementDate', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['executionId'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_movement_execution_key', 'credit_movement', ['executionId', 'key'], unique=False)
    op.create_table('pending_case',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('executionId', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('posId', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('accountNumber', sa.String(), nullable=False),
    sa.Column('simoAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bankaAmount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('type', sa.Enum('missing', 'mismatch', name='case_type'), nullable=False),
    sa.Column('eTicket', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'resolved', name='case_status'), nullable=False),
    sa.Column('resolvedAt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['executionId'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('executionId', 'key', name='uq_pending_case_execution_key')
    )
    op.create_index('ix_pending_case_execution_status', 'pending_case', ['executionId', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_case_execution_status', table_name='pending_case')
    op.drop_table('pending_case')
    op.drop_index('ix_credit_movement_execution_key', table_name='credit_movement')
    op.drop_table('credit_movement')
    op.drop_index('ix_closing_detail_execution_validation', table_name='closing_detail')
    op.drop_index('ix_closing_detail_execution_pos_id', table_name='closing_detail')
    op.drop_index('ix_closing_detail_execution_key', table_name='closing_detail')
    op.drop_table('closing_detail')
    op.drop_index(op.f('ix_execution_executedAt'), table_name='execution')
    op.drop_table('execution')
    # ### end Alembic commands ###
